- src/github.com/arduino-libraries/WiFi101-FirmwareUpdater/cli/main/winc1500-uploader.go
allows to use both commands in the same command line preventing certificates from being deleted when the firmware is flashed
> Reversing the order of the flashCerts() and flashFirmware() functions

- modules/nina/main.go
During a bug 🐛  hunt with @AlbyIanna we discovered that on windows (*obviously*), if paths are not specified correctly the FirmwareUpdater was crashing with a panic (`panic: runtime error: invalid memory address or nil pointer dereference`). The problem was that the flag `-programmer` was indicating something meaningless like `C:/Users/Umberto`.
> log and exit if programmer is not specified correctly

- .github/workflows/check-certificates.yml
- .github/workflows/check-notarization-certificates.yml
- .github/workflows/link-validation.yml
- .github/workflows/release.yml
- .gitignore
- README.md
- Taskfile.yml
- go.mod
- gon.config.hcl
- main.go
- modules/nina/flasher.go
- modules/nina/main.go
- modules/sara/flasher.go
- modules/sara/main.go
- modules/winc/flasher.go
- modules/winc/main.go
- programmers/avrdude/avrdude.go
- programmers/bossac/bossac.go
Updated binary name (from FirmwareUpdater to FirmwareUploader) in the CI / Taskfiles / .gitignore.
I think it's a bit confusing to use both FirmwareUploader and FirmwareUpdater in the same GitHub repo though.. I've renamed also the repo handle. The only thing missing is to rename the repo name in settings.
> Rename FirmwareUpdater to FirmwareUploader

- .github/workflows/release.yml
The mac binary (version 0.1.4) does not have executable permission. This PR fixes this behavior.
Just like in the [arduino-cli](https://github.com/arduino/arduino-cli/blob/master/.github/workflows/release.yaml#L87)
> fix CI not setting executable permission to mac binary

- .github/workflows/link-validation.yml
- .github/workflows/release.yml
- .github/workflows/test.yaml
- .github/workflows/verify-formatting.yml
The GitHub Actions action for installing [Task](https://taskfile.dev/#/) has graduated from its original home in [the experimental `arduino/action`repository](https://github.com/arduino/actions) with a move to a dedicated permanent repository at [`arduino/setup-task`](https://github.com/arduino/setup-task).
A [1.0.0 release](https://github.com/arduino/setup-task/releases/tag/v1.0.0) has been made and [a `v1` ref](https://github.com/arduino/setup-task/tree/v1) that will track all releases in the major version 1 series. Use of the action's major version ref will cause the workflow to benefit from ongoing development to the action at each [patch or minor release](https://semver.org/) up until such time as a new major release is made. At this time the user will be given the opportunity to …
> Use new arduino/setup-task action name in CI/CD workflows

- cli/cli.go
- cli/version/version.go
- version/version.go
```
./FirmwareUploader version
FirmwareUploader Version: git-snapshot Commit: 9e267c9 Date: 2021-05-21T17:16:47Z
```
> add `version` subcommand

- cli/cli.go
- cli/version/version.go
- go.mod
- go.sum
I've added the `--format` persistent flag (it should be available in all the subcommands). You can now specify the program output with either `json` or `text`(the default value). For now the only command supported is `version`. Other commands will use this enhancement. In the near future.
> add `--format` flag, predisposition to print json, like arduino-cli

- generator/generator.py
- generator/raw_boards.json
The `generator.py` script creates a `board_index.json` file that will be used by the FirmwareUploader tool to gather all the information necessary to run correctly, list of firmwares for each supported board, upload command to run, binary to loader Sketch. It also copies the necessary firmware and loader Sketch binaries in structured folders ready to be uploaded in the download server.
As of now it uses a `raw_board.json` file that has been created using some information obtained using the `--get_available_for` flag that returns all available firmware for all each supported board.
In the future we can use the `board_index.json` currently in use as a base and add new information if necessary.
The script assumes the Arduino CLI is installed and all supported boards' core too, it fails in …
> Add script to generate json containing information to run fwuploader tool

- generator/generator.py
- generator/raw_boards.json
Now `generator.py` replaces all the necessary parameters in the `uploader.command` field so the `fwuploader` will be able to run the upload tool, if that is not done the `fwuploader` simply lacks the information necessary to replaces those parameters since they're stored in various cores' `boards.txt` and `platform.txt`. The `fwuploader` assumes no core is installed so this had to be done.
I also had to handle a corner case for the Arduino Uno WiFi Rev2 since the `upload.pattern` in the `arduino:megaavr` core's `platform.txt` also assumes the bootloader will be uploaded, I solved this by compiling a Loader Sketch that includes the bootloader and by removing the `upload.extra_files` parameter.
Also I fixed all paths in the `raw_boards.json` since they were using my own environment paths, …
> Fix some issues with board index generator script

- cli/cli.go
- go.mod
- go.sum
Add logging support and related flags:
- `log-file` to specify path to file where logs will be written to
- `log-format` to set the format of the logging output, either `text` or `json`
- `log-level` the minimum log level of messages that must be shown, levels are `trace`, `debug`, `info`, `warn`, `error`, `fatal`, `panic`. Defaults to `info`
- `verbose` to print logs to standard output
> [skip changelog] Add logging support

- generator/generator.py
We chose another name for the json file that will contain the informations necessary for the `FirmwareUploader` to run correctly.
> [skip changelog] Change name of generated index json

- cli/certificates/certificates.go
- cli/certificates/flash.go
- cli/cli.go
`certificates flash` command is used to flash certificates to the specified board connected on the specified address.
It supports four flags:
- `--fqbn`, `-b`, Fully Qualified Board Name, e.g.: `arduino:samd:mkr1000`, `arduino:mbed_nano:nanorp2040connect`
- `--address`, `-a`, Upload port, e.g.: COM10, /dev/ttyACM0
- `--url`, `-u`, List of urls to download root certificates, e.g.: arduino.cc:443
- `--file`, `-f`, List of paths to certificate file, e.g.: /home/me/Digicert.cer
Multiple urls or files can be specified to flash them at the same time.
Example commands:
```
FirmwareUploader certificates flash --fqbn arduino:samd:mkr1000 --address COM10 --url arduino.cc:443 --file /home/me/Digicert.cer
FirmwareUploader certificates flash -b arduino:samd:mkr1000 -a COM10 -u arduino.cc:443 -u …
```
> Add `certificates flash` command

- cli/certificates/flash.go
- cli/firmware/flash.go
Solved a bug that caused a panic when a mkr1000 is used. The module name in `module_firmware_index.json` (WINC1500) was different from a check in the code (WINC)
> fix 🐛 causing panic with mkr1000

- cli/certificates/flash.go
- cli/firmware/flash.go
It's possible, especially on Win, that the board changes port after a reset. Now the new port is used after resetting it.
I also incremented the waiting time between the loader flashing and the actual firmware update. The time was not sufficient for the board to be available again.
> harden the flashing process

- cli/firmware/flash.go
Add `--retries` flag just like in #24.
We removed this behavior during the refactoring.
Basically, the FirmwareUploader tries to update the firmware 9 times in a row (by default). Sometimes there could be some failings because of programmer out of sync, serial port closing etc… With this flag, the process should be more reliable
> add back `--retries` flag 

- DistTasks.yml
The firmware files are now hosted on our download servers and are fetched automagically by the `arduino-fwuploader` during the flashing process. They are not used anymore by the user.
> remove firmwares dir from released archives (not useful anymore)

- DistTasks.yml
We set variables containing information regarding version, commit and build time. These variables were set in the `Taskfile.yml` but not in the `DistTask.yml` (the one used in the CI)
> fix `version` command not working correctly in the released binary

- cli/firmware/flash.go
- flasher/flasher.go
- flasher/nina.go
- flasher/winc.go
Before the refactoring, the progress of the firmware flashing was showing. We removed it during the refactoring. I'm adding it back now.
fixes #67
> add progress during firmware flashing

- flasher/flasher.go
- go.mod
- go.sum
This PR expands #68 by upgrading the golang serial library to allow non-standard baudrates in macosx.
> fix uno wifi rev 2 not working (round 2)

- docs/usage.md
`commands/arduino-fwuploader.md` do not exist when running link-validation workflow. Using full URL instead should fix the problem
> [skip-changelog] fix link validation workflow

- cli/firmware/flash.go
Expands and completes #58
On windows when the board is touched at 1200bps it goes in bootloader mode (on a different COM port).
I used the correct approach in #58, but I forgot that the `commandLine` variable was being set before.. 🤦 
The working principle is the following:
1. The board (a samd once) is present on COM6 for example
2. The board is touched at 1200bps
3. The board comes bach online on a different COM (for example COM7)
4. The uploader sketch must be uploaded keeping in mind this behaviur
5. After the upload is complete **the board returns to the previous COM port** (in our example COM6) <- we were not considering this
6. We open a serial connection to COM6 at 1000000bps to upload the firmware binary to the board.
7. The end 🪂
> harden the flashing process on win pt2

- Taskfile.yml
- docs/usage.md
Some links may point to the generated documentation content, which would result in a failure of the link check.
It's true that these links are indeed broken when accessed outside the website, but the primary publishing location for
this content is the website. The alternative would be checking the generated content into the repository, but this would
either require some fairly complex automation or else a burden on the contributors to keep it synced.
> Generate documentation before running link check

- README.md
Before releasing 1.0.0 the latest redirect did not exist. Now that it is available, it's better to point to that
> [skip-changelog] change docs link: point to latest version

- .github/workflows/generate-index.yml
The workflow trigger was set to the wrong base branch
> [skip-changelog] fix wrong workflow trigger

- cli/certificates/flash.go
I forgot to apply the fix from #76 to the certificate flashing :facepalm:
> harden cert flash on windows pt3 (was using port before touch)

- .github/workflows/check-certificates.yml
- .github/workflows/check-notarization-certificates.yml
We have assembled a collection of reusable GitHub Actions workflows:
https://github.com/arduino/tooling-project-assets
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" workflow, and those are introduced
to this repository here.
Notable:
- Run workflows on their modification when possible to facilitate development and review
- Run "Check Certificates" workflow on certificate file modification
- Allow triggering workflows via GitHub API
- Improved readability of matrix job names
- Use Slack webhook secret name more appropriate for general application of the "template" workflow
- Use major version ref of `rtCamp/action-slack-notify` action for automatic updates to all its …
> Sync certificate check workflows with "template"

- Taskfile.yml
- go.sum
The `go list` command used to set the dynamic taskfile variable to the path of the golint installation does not work in
the "module-aware mode" that is now Go's default (and only in 1.17). Causing every task to fail after the module has been
tidied:
```
$ go mod tidy && task build
missing go.sum entry for module providing package golang.org/x/lint/golint; to add:
go mod download golang.org/x/lint
task: Command "go list -f {{".Target}}" golang.org/x/lint/golint" failed: exit status 1
```
In the end, I gave up on making it work as before. I think it's better to require the user to install golint and put the
installation in the system `PATH`, making the linting task display a helpful message when this has not been done.
> Make taskfile compatible with Go 1.16

- .github/workflows/publish-go-tester-task.yml
On every commit to a pull request or the repository:
- Build the project for all supported platforms.
- Upload the builds as workflow artifacts.
This makes it possible for any interested party to participate in beta testing without setting up a build system locally.
> Add CI workflow to publish tester builds

- .github/workflows/release-go-task.yml
- Taskfile.yml
- gon.config.hcl
We have assembled a collection of reusable project assets:
https://github.com/arduino/tooling-project-assets
These assets will be used in the repositories of all Arduino tooling projects.
Some improvements and standardizations have been made in the upstream "template" release assets, and those are introduced
to this repository here.
Notable:
- Handle signed commits (https://github.com/arduino/arduino-cli/pull/1344)
- Make changelog generation system work correctly for pre-releases (https://github.com/arduino/arduino-cli/pull/1284)
- Improve failure detection
---
Demo release from my fork:
https://github.com/per1234/arduino-fwuploader/actions/runs/1131445405
https://github.com/per1234/arduino-fwuploader/releases/tag/2.2.2
> Sync release assets with templates

- .github/workflows/check-go-cross-build-task.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
- README.md
- Taskfile.yml
- poetry.lock
- pyproject.toml
- test/conftest.py
- test/pytest.ini
We have assembled a collection of reusable project assets:
https://github.com/arduino/tooling-project-assets
These assets will be used in the repositories of all Arduino tooling projects.
Some improvements and standardizations have been made in the upstream "template" testing assets, and those are introduced
to this repository here.
Notable:
- Split into separate workflows for each distinct testing type
- Use Codecov to track code coverage
- Make integration test work directory path canonical
- Do clean up of integration test work directory
- Update integration test dependencies
Some task names have changed:
- `test-unit` -> `go:test`
- `test-integration` -> `go:test-integration`
> Sync testing assets with templates

- .github/workflows/check-go-cross-build-task.yml
- .github/workflows/publish-go-tester-task.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
The [trunk-based development](https://trunkbaseddevelopment.com/) strategy is used by this project. The release branch may contain a subset of the history of the default branch.
The status of the GitHub Actions workflows should be evaluated before making a release. However, this is not so simple as checking the status of the commit at the tip of the release branch. The reason is that, for the sake of efficiency, the [workflows are configured](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) to run only when the processes are relevant to the trigger event (e.g., no need to run unit tests for a change to the readme).
In the case of the default branch, you can simply [set the workflow runs filter to that …
> Run relevant workflows on release branch creation

- .github/workflows/generate-index.yml
The **Board** field when running `arduino-fwuploader firmware list`
```
$ arduino-fwuploader firmware list -b arduino:mbed_nano:nanorp2040connect
Board FQBN                                Module   Version
arduino:mbed_nano:nanorp2040connect NINA     1.4.5  
arduino:mbed_nano:nanorp2040connect NINA     1.4.6  
arduino:mbed_nano:nanorp2040connect NINA     1.4.7  
arduino:mbed_nano:nanorp2040connect NINA   ✔ 1.4.8
```
I have opened an issue on the `arduino-cli` repo because apparently the problem comes from it:
https://github.com/arduino/arduino-cli/issues/1401
The cli is used to obtain the name of the board, by the generator, which is run by the CI in the `generate-index.json` workflow. This is only a temporary fix, while we wait for the fix in `arduino-cli`
This is the diff before and …
> bump mbed core to latest

- cli/arguments/arguments.go
- cli/certificates/flash.go
- cli/common/common.go
- cli/firmware/firmware.go
- cli/firmware/flash.go
- cli/firmware/getversion.go
- docs/usage.md
- flasher/flasher.go
- flasher/nina.go
- flasher/winc.go
- indexes/download/download.go
- indexes/download/download_test.go
- indexes/firmwareindex/firmwareindex.go
- version/version.go
I have added a new sub-command to be able to retrieve the firmware version in use by a module.
During the process, I refactored a bit the code, since there were useless repetitions. 
Docs have been added
> add `get-version` command 

- cli/firmware/flash.go
- docs/usage.md
With this enhancement, a custom local firmware can be uploaded to a board using `-i` or `--input-file` flag:
``` 
./arduino-fwuploader firmware flash -i custom_fw.bin -b arduino:samd:mkr1000 -a /dev/ttyACM0
```
> add `-i` flag to upload a custom fw to a board

- indexes/download/download.go
This allows to verify the checksum of files downloaded on the fly without the need to store them in some file-system directory
> Add generic function to verify checksum

- .github/workflows/check-go-cross-build-task.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
This reverts commit f9aa597679b6ee3207d156a676388750368d262d.
Related to https://github.com/arduino/tooling-project-assets/pull/186
> [skip-changelog] Revert "pin task version in workflows running on windows"

- cli/firmware/list.go
> fix panic when cannot download FirmwareIndex

- docs/usage.md
> expand the documentation regarding the certificates flashing

- Taskfile.yml
Probably some leftover from some copy/paste. The removed tasks were not working and should be superseded by  `markdown:` ones
> remove old unused tasks, .PRETTIER was not even defined

- .licenses/go/golang.org/x/sys/internal/unsafeheader.dep.yml
- .licenses/go/golang.org/x/sys/unix.dep.yml
- docs/usage.md
- docsgen/go.sum
- flasher/nina.go
- flasher/winc.go
- go.mod
- go.sum
Before this change, only `.cer` certificate support was supported. With this also the `.pem` encoded one are supported. The doc has been updated accordingly
> add support for `.pem` cert format

- .github/workflows/check-go-dependencies-task.yml
A "Check Go Dependencies" GitHub Actions workflow is used to check whether all Go package dependencies of the modules in this repository use compatible licenses.
This workflow is hosted and maintained in a repository dedicated to a collection of such reusable Arduino tooling project assets.
Several enhancements have been made to the upstream file, but those had not yet been pulled into this repository:
- Bump action dependencies
- Correct and improve reference links:
- https://github.com/arduino/tooling-project-assets/commit/e5dc77ebc43394a493771d54ae33997520162040
- https://github.com/arduino/tooling-project-assets/commit/756af2a3feb7b408b9dd050c7c7d2a5ab24a49ca
- Detect unused dependency license metadata files
https://github.com/arduino/tooling-project-assets/commit/0a66312592f9b2ff227a7 …
> [skip changelog] Sync "Check Go Dependencies" workflow with upstream

- extras/package_index.json.template
The correct target listed by `gcc` is `arm64-apple-darwin...` and not `aarch64-apple-darwin...`. See also https://github.com/arduino/arduino-cli/blob/10107d2407c2d9997310fc2e0f22dfd15d48e9a8/arduino/cores/tools.go#L135.
> fix darwin m1 host name

- .github/workflows/check-notarization-certificates.yml
The "Check Notarization Certificates" GitHub Actions workflow uses [**OpenSSL**](https://www.openssl.org/) to check for problems with the project's signing certificates.
Certificates exported to [PKS #12](https://en.wikipedia.org/wiki/PKCS_12) archive files using older tools may have been encrypted using the ["RC2-40-CBC" algorithm](https://en.wikipedia.org/wiki/RC2).
Due to the availability of more secure modern alternatives, [default support for "RC2-40-CBC" encryption was dropped in **OpenSSL** 3.x](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#PKCS-12-API-updates).
This project's macOS signing certificate uses "RC2-40-CBC" encryption.
The "Check Notarization Certificates" GitHub Actions workflow runs on [the `ubuntu-latest` …
> Restore certificate check compatibility w/ RC2-40-CBC encrypted PKS#12

- indexes/download/download.go
- indexes/indexes.go
- indexes/indexes_test.go
Code imperfection fix
Temporary files and directories created running the command `arduino-fwuploader firmware list` are not cleaned up on exit. There are two reasons behind this behavior. The temporary directory with a name format `55770067919477794103602099745` is not cleaned up because the `DownloadIndex()` function is trying to remove an empty directory (which is not), silently failing while doing so.  On the other hand, the removal of `fwuploader` is never addressed.
Temporary files and directories are correctly cleaned up on exit.  The directory named `fwuploader` is removed by the function `GetFirmwareIndex()` because doing it prematurely in `DownloadIndex()` would cause the command to fail.
> Clean up temporary files on exit

- .github/workflows/check-go-dependencies-task.yml
- .github/workflows/check-notarization-certificates.yml
- .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
- .github/workflows/generate-index.yml
- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release-go-crosscompile-task.yml
- .github/workflows/sync-labels.yml
- .github/workflows/test-go-integration-task.yml
- .github/workflows/test-go-task.yml
- DistTasks.yml
- Taskfile.yml
The assets used to produce the project's release and tester builds are based on reusable "templates" maintained in a centralized repository:
https://github.com/arduino/tooling-project-assets
Some advancements have been made to those upstream templates. Those are here pulled down to this repository.
Although the focus here is on the build assets, I applied some of the categories of changes universally (see the PR's individual commits for details).
---
Test release done using the updated assets:
- https://github.com/per1234/arduino-fwuploader/actions/runs/4352382634
- https://github.com/per1234/arduino-fwuploader/releases/tag/0.0.0-rc.2
- https://github.com/arduino/tooling-project-assets/pull/326
- https://github.com/arduino/tooling-project-assets/pull/277
- …
> Sync build assets from templates

- .github/workflows/check-markdown-task.yml
- .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
The project documentation is published on [a companion website](https://arduino.github.io/arduino-fwuploader/dev/). A GitHub Actions workflow is used to automatically update the website whenever any relevant file is changed in the repository. This website includes [content generated from the project's Go code](https://arduino.github.io/arduino-fwuploader/dev/commands/arduino-fwuploader/).
Previously, the default version of Go from the GitHub Actions runner machine was used for generating the documentation content. A recent update of this default Go version from 1.17 to 1.20 (https://github.com/actions/runner-images/issues/7276) caused the generation process to fail:
https://github.com/arduino/arduino-fwuploader/actions/runs/4923760846/jobs/8795964719#step:4:39
```text
panic: runtime …
```
> Use project Go version for generating website content

- cli/firmware/flash.go
- cli/firmware/getversion.go
- plugin/plugin.go
Add support for https://github.com/arduino/fwuploader-plugin-helper/pull/9
> pass `--fqbn` to plugin

- .licensed.yml
- .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/cores/packagemanager.dep.yml
- .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/discovery.dep.yml
- .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/discovery/discoverymanager.dep.yml
- .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/sketch.dep.yml
- .licenses/arduino-fwuploader/go/github.com/arduino/go-timeutils.dep.yml
- .licenses/arduino-fwuploader/go/golang.org/x/exp/constraints.dep.yml
- .licenses/arduino-fwuploader/go/golang.org/x/exp/slices.dep.yml
- .licenses/arduino-fwuploader/go/gopkg.in/yaml.v3.dep.yml
- certificates/certutils.go
- cli/certificates/flash.go
- cli/cli.go
- cli/common/common.go
- cli/firmware/flash.go
- cli/firmware/getversion.go
- cli/firmware/list.go
- cli/globals/globals.go
- flasher/nina.go
- flasher/winc.go
- go.mod
- go.sum
- indexes/download/download.go
- indexes/firmwareindex/firmwareindex.go
- indexes/firmwareindex/firmwareindex_test.go
- indexes/indexes.go
- indexes/indexes_test.go
- plugin/plugin.go
This PR adds a new kind of upload method based on a "plugin" system. A documentation for this system is being produced, anyway, for the sake of this PR, I'm describing it briefly.
A "firmware uploader plugin" is a command line tool that has a specific command line syntax:
```
./fwuploader-plugin version
./fwuploader-plugin firmware get-version -p PORT -b FQBN -v --log-level LEVEL
./fwuploader-plugin firmware flash -p PORT -b FQBN -v --log-level LEVEL FIRMWARE_PATH
./fwuploader-plugin cert flash -p PORT -b FQBN -v --log-level LEVEL CERT_BUNDLE_PATH
```
The list of available plugins and firmware will be placed in a specific `plugin_firmware_index.json`. The plugin is downloaded exactly the same as any other tool from the Arduino package index. Each plugin may depend on other upload tools …
> Introducing plugins system

- flasher/winc.go
Fixed a regression in the winc flasher when trying to upload .pem files
> Fix regression on winc when flashing pem certificates

- mkdocs.yml
The project documentation is published in a website generated by [**MkDocs**](https://www.mkdocs.org/).
The primary UI for discovering and accessing the various pages of the site is through the navigation panel/menu. In order to have control over the structure, the contents of the navigation element are explicitly defined in the `nav` key of the MkDocs configuration file:
https://www.mkdocs.org/user-guide/configuration/#nav
A new "Plugins" page was added to the documentation (https://github.com/arduino/arduino-fwuploader/pull/179). Previously that page it was not included in the `nav` key so the page was not listed in the website's navigation element.
The navigation element before the changes proposed here:
and after:
> Add "Plugins" page to the website navigation panel

- generator/generator.py
- generator/new_boards.json
Before this we have to have the core installed to retrieve this info. It's not optimal to install a whole core for a name only.
This problem became clear when running: `arduino-fwuploader firmware list`:
```
Board                       FQBN                                Module     Version
[...]
Arduino MKR WiFi 1010       arduino:samd:mkrwifi1010            NINA     ✔ 1.5.0
[...]
Arduino Uno WiFi Rev2       arduino:megaavr:uno2018             NINA     ✔ 1.5.0  
[...]
Arduino Nano RP2040 Connect arduino:mbed_nano:nanorp2040connect NINA       1.4.8  
Arduino Nano RP2040 Connect arduino:mbed_nano:nanorp2040connect NINA     ✔ 1.5.0  
arduino:renesas_uno:unor4wifi       ESP32-S3   0.1.0  
arduino:renesas_uno:unor4wifi       ESP32-S3   0.2.0  
arduino:renesas_uno:unor4wifi       ESP32-S3 ✔ …
```
> Fix the name not being present on the index

- certificates/certutils.go
Disabling TLS/SSL certificate verification might lead to attack scenarios where an attacker is able to install rouge certificates on the Arduino board. The attacker would need to be within network proximity of the victim to perform the attack.
> Fix Improper Certificate Validation

- indexes/download/download.go
- indexes/download/download_test.go
The fwuploader currently crashes if a tool is not available for the OS. With this fix, it throws an error instead.
> Throw an error when a tool has no compatible flavour with the current OS

- cli/certificates/flash.go
Previously, if there was a problem during the flashing stage of the certificate flash command invocation, Arduino Firmware Uploader would exit silently, giving the user no feedback that something had gone wrong other than a generic exit status 1:
```text
$ touch /tmp/cert-with-unsupported-extension.crt
$ arduino-fwuploader certificates flash --address COM42 --file /tmp/cert-with-unsupported-extension.crt --fqbn arduino:renesas_uno:unor4wifi
Converting and flashing certificate C:/Users/per/AppData/Local/Temp/cert-with-unsupported-extension.crt
$ echo $?
1
```
After the change proposed here, Arduino Firmware Updater clearly communicates to the user that the command failed, and why:
```text
$ arduino-fwuploader certificates flash --address COM42 --file …
```
> Print error message on certificate flash failure

- certificates/certutils.go
- certificates/certutils_test.go
- cli/certificates/flash.go
- docs/plugins.md
After #212 we can leverage the usage of [ConnectionState.VerifiedChains](https://pkg.go.dev/crypto/tls@go1.21.0#ConnectionState) and per docs:
> last element is from Config.RootCAs
So the last element of the VerifiedChains will be the actual RootCA!
> Fix wrong scrape of Root Certificates

- .github/workflows/release-go-crosscompile-task.yml
An excellent tool named [gon](https://github.com/mitchellh/gon) was used to perform the notarization.
the latest stable release of gon uses the altool command-line utility for notarization:
https://github.com/mitchellh/gon/blob/v0.2.5/notarize/upload.go#L41
Using altool for notarization is now deprecated by Apple and support for notarization via this tool is scheduled to be disabled 2023-11-01:
https://developer.apple.com/news/?id=y5mjxqmn
Furthermore, gon was archived.
I switched to https://github.com/Bearer/gon that has included https://github.com/mitchellh/gon/pull/72, hoping the maintainers will take the responsibility of maintaining the project.
I added also `AC_PROVIDER` env var which is mandatory with the new notarytool.
See …
>  Replace mitchellh/go used for macOS notarization

- .github/workflows/generate-index.yml
While carrying on #240 I forgot to update this workflow. Now it uses OIDC to retrieve the short-lived credential like the release one.
> use OIDC to retrieve the credentials, fixup for #240

- .github/workflows/check-go-dependencies-task.yml
A breaking change was made in the 3.2.1 release of the [**actions/upload-artifact**](https://github.com/actions/upload-artifact) action (https://github.com/actions/upload-artifact/issues/602), without doing a major version bump as would be done in a responsibly maintained project. The action now defaults to not uploading "hidden" files.
This project's "**Check Go Dependencies**" workflow uses the [**Licensed**](https://github.com/github/licensed) tool to check for incompatible dependency licenses. The dependencies license metadata cache used by **Licensed** is stored in a folder named `.licensed`.
In order to facilitate updates, the workflow uploads the generated dependencies license metadata cache as a [workflow artifact](https://docs.github.com/actions/writing-workflows/choosing-what-you …
> [skip changelog] Configure actions/upload-artifact action to upload required hidden files

- .github/workflows/check-mkdocs-task.yml
- .github/workflows/check-prettier-formatting-task.yml
- .github/workflows/test-go-task.yml
This repository contains several GitHub Actions workflows to facilitate the development and maintenance of the project.
The workflows are typically configured to run whenever any relevant file in the repository is changed. However, the results of the workflow run are also dependent on the external environment it runs in, which include:
- The software running on the GitHub hosted GitHub Actions runner machines
- The GitHub Actions actions used by the workflow
- The dependencies that are installed by the workflow directly or via the GitHub Actions actions it uses
The workflows don't always fully pin dependencies. This was done in the interest on reducing the maintenance burden of keeping the systems up to date. However, it also means that a new release of a dependency can cause the workflow …
> Add missing schedule triggers to workflows

- .github/workflows/test-go-integration-task.yml
The integration tests run automatically via a GitHub Actions workflow.
The workflows are typically configured to run whenever any relevant file in the repository is changed. However, the results of the workflow run are also dependent on the external environment it runs in, which include:
- The software running on the GitHub hosted GitHub Actions runner machines
- The GitHub Actions actions used by the workflow
- The dependencies that are installed by the workflow directly or via the GitHub Actions actions it uses
The workflows don't always fully pin dependencies. This was done in the interest on reducing the maintenance burden of keeping the systems up to date. However, it also means that a new release of a dependency can cause the workflow runs to start failing (which might happen …
> Add missing schedule trigger to workflow

- .prettierignore
- Taskfile.yml
- package-lock.json
- package.json
The project uses the [**Prettier**](https://prettier.io/) tool to format various file types. Previously, the version of the tool used was not controlled. This was problematic because:
- A different version of the tool may be used on the contributor's machine than on the CI runner, resulting in confusing failures.
- The project is immediately subject to disruption or breakage resulting from a release of the tool.
The new approach is to specify the version of the tools via the standard npm metadata files (`package.json` + `package-lock.json`), providing the following benefits:
- Enables automated updates via Dependabot PRs
- Enables automated vulnerability alerts
> Use npm to manage Prettier tool dependency

- README.md
- docs/deprecated.md
The Prettier tool is used to format the project's Markdown files. Prettier's word wrapping system seems to have changed in a recent release. This caused the "Check Prettier Formatting" GitHub Actions workflow to start failing due to the formatting of some Markdown files no longer being in compliance with the Prettier formatting style.
> Bring files into compliance with latest Prettier formatting style

- .github/workflows/publish-go-tester-task.yml
- .github/workflows/release-go-crosscompile-task.yml
GitHub Actions workflows are used to automatically generate beta tester and production builds of the project.
While starting the work to update the workflow code for compatibility with the breaking change introduced in the latest versions of the **actions/upload-artifact** action (https://github.com/arduino/arduino-fwuploader/pull/233), I found that it was quite difficult to follow the workflow code due to the way some variables were defined. The refactoring proposed here is intended to improve the maintainability and readability of the workflows:
A separate build is generated for each of the target host types. This is done using a job matrix, which creates a parallel run of the workflow job for each target. The matrix defines variables that provide the data that is specific to each job. …
> Refactor variables in release workflows

- .licenses/arduino-fwuploader/go/github.com/mattn/go-colorable.dep.yml
- .licenses/arduino-fwuploader/go/go.bug.st/cleanup.dep.yml
- .licenses/arduino-fwuploader/go/go.bug.st/downloader/v2.dep.yml
- .licenses/arduino-fwuploader/go/google.golang.org/protobuf/internal/encoding/json.dep.yml
- .licenses/arduino-fwuploader/go/google.golang.org/protobuf/internal/impl.dep.yml
- .licenses/arduino-fwuploader/go/google.golang.org/protobuf/types/descriptorpb.dep.yml
- .licenses/arduino-fwuploader/go/google.golang.org/protobuf/types/known/wrapperspb.dep.yml
The [**Licensed**](https://github.com/licensee/licensed) tool is used to check for incompatible licenses in the project dependencies. The tool relies on a cache of metadata stored in the repository.
An older version of **Licensed** was in use at the time the cache was established. There are some minor differences in the format of the metadata generated by the version of **Licensed** currently in use.
Previous versions of this tool added a trailing space on the `summary` key. Although trailing whitespace in human produced content is not permitted, machine generated content is used as-is, and so these trailing spaces were left in the metadata files.
It seems that the defect in the "Licensed" tool that caused the trailing space was fixed in a recent version because it is now absent in the …
> Update format of dependency license metadata
